
CREATE DATABASE MST;

USE MST;

--ENSURE THAT THE NAMES HERE CORRESPOND WITH THE NAMES IN THE ERD

--TABLE CREATION
--ADD NOT NULL FOR FK MAYBE, MAYBE ADD FOREGIN KEY CONTRAINT AFTER
-- TO IMPLEMENT 1:M M:M ETC THE FK ARENT ALWAYS REFERENCED IN EACH TABLE CHECK WEBSITE 
-- THERES TOO MANY FKS, FOR EACH FOREIGN KEY YOU NEED TO HAVE A LINK.

--ALTER DATABASE MST SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
--DROP DATABASE MST;


CREATE TABLE GUIDE(
	GUIDE_ID CHAR(9) PRIMARY KEY,
	QUALIFICATION_ID CHAR(9),
	FULL_NAME VARCHAR(100) NOT NULL, --INCLUDES FNAME, LNAME
	HIRED_DATE DATE NOT NULL,
	CONSTRAINT CHK_HIRED_DATE CHECK (HIRED_DATE <= CAST(GETDATE() AS DATE)),
	ADDRESS VARCHAR(100) -- INCLUDES STRT_NO, STRT_NAME, CITY, ZIP
);


CREATE TABLE TOUR(
	TOUR_ID CHAR(9) PRIMARY KEY,
	NAME CHAR(25) NOT NULL, 
	DURATION TIME,
	FEE NUMERIC NOT NULL,
	CREATED_DATE DATE NOT NULL,
	CONSTRAINT CHK_TOUR_CREATED_DATE CHECK (CREATED_DATE <= CAST(GETDATE() AS DATE))
);


CREATE TABLE LOCATION(
	LOCATION_ID CHAR(9) PRIMARY KEY,
	NAME VARCHAR(25) NOT NULL,
	TYPE VARCHAR(25),
	DESCRIPTION VARCHAR(50),
	ADDRESS VARCHAR(100) -- INCLUDES STRT_NO, STRT_NAME, CITY, ZIP

);


CREATE TABLE VISIT(
	TOUR_ID CHAR(9), --FK
	CONSTRAINT FK_VISIT_TOUR_ID FOREIGN KEY (TOUR_ID) REFERENCES TOUR,
	LOCATION_ID CHAR(9), --FK
	CONSTRAINT FK_VISIT_LOCATION_ID FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION,
	CONSTRAINT PK_VISIT_TOUR_LOCATION PRIMARY KEY(TOUR_ID, LOCATION_ID) --PK
);


CREATE TABLE QUALIFICATION(
	TOUR_ID CHAR(9), --FK
	CONSTRAINT FK_QUALIFICATION_TOUR_ID FOREIGN KEY (TOUR_ID) REFERENCES TOUR,
	GUIDE_ID CHAR(9), --FK
	CONSTRAINT FK_QUALIFICATION_GUIDE_ID FOREIGN KEY (GUIDE_ID) REFERENCES GUIDE,
	CONSTRAINT PK_QUALIFICATION_TOUR_GUIDE PRIMARY KEY(TOUR_ID, GUIDE_ID), --PK
	TEST_DATE DATE NOT NULL

);

CREATE TABLE TRIP(
	TRIP_ID CHAR(9) PRIMARY KEY,
	TOUR_ID CHAR(9), --FK
	CONSTRAINT FK_TRIP_TOUR_ID FOREIGN KEY (TOUR_ID) REFERENCES TOUR,
	GUIDE_ID CHAR(9), --FK
	CONSTRAINT FK_TRIP_GUIDE_ID FOREIGN KEY (GUIDE_ID) REFERENCES GUIDE,
	TRIP_DATE DATE,
	SCHEDULED_TIME TIME, -- CHANGE NAME IN ERD
	CREATED_DATE DATE NOT NULL,
	CONSTRAINT CHK_TRIP_CREATED_DATE CHECK (CREATED_DATE <= CAST(GETDATE() AS DATE))
);


CREATE TABLE TOURIST(
	TOURIST_ID CHAR(9) PRIMARY KEY,
	TRIP_ID CHAR(9), --FK
	CONSTRAINT FK_TOURIST_TRIP_ID FOREIGN KEY (TRIP_ID) REFERENCES TRIP, 
	TRANSACTION_ID CHAR(9), --FK
	FULL_NAME VARCHAR(100) NOT NULL, --INCLUDES FNAME, LNAME
	ADDRESS VARCHAR(100) -- INCLUDES STRT_NO, STRT_NAME, CITY, ZIP

);


CREATE TABLE TRANSACTIONS(
	TRANSACTIONS_ID CHAR(9) PRIMARY KEY,
	TOURIST_ID CHAR(9), --FK
	CONSTRAINT FK_TRANSACTIONS_TOURIST_ID FOREIGN KEY (TOURIST_ID) REFERENCES TOURIST,
	TRIP_ID CHAR(9), --FK
	CONSTRAINT FK_TRANSACTIONS_TRIP_ID FOREIGN KEY (TRIP_ID) REFERENCES TRIP,
	CARD_INFO VARCHAR(100) UNIQUE  --INCLUDES:
						    --PAYMENT_METHOD CHAR(25),
							--CARD_NO INT,
							--EXPIRATION_DATE DATE,
							--CVC INT,
							--CARD_HOLDER CHAR(25)
);


-- CONTRAINTS

ALTER TABLE GUIDE
ADD CONSTRAINT FK_GUIDE_QUALIFICATION_ID FOREIGN KEY (QUALIFICATION_ID) REFERENCES QUALIFICATION;

ALTER TABLE TOURIST
ADD CONSTRAINT FK_TOURIST_TRANSACTION_ID FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTIONS;
